<template>
    <!-- TODO: set as a layout -->
    <Navigation/>
    <div>An about page</div>
    <div>An about page</div>
    <div>An about page</div>
    <div>An about page</div>
    <div>An about page</div>
    <div>An about page</div>
    <div>An about page</div>
    <div>An about page</div>
    <div>An about page</div>
    <div>An about page</div>
    <div>An about page</div>
    <div>An about page</div>
    <div>An about page</div>
    <div>An about page</div>
    <div>An about page</div>
    <div>An about page</div>
    <div>An about page</div>
    <div>An about page</div>
    <div>An about page</div>
    <div>An about page</div>
    <div>An about page</div>
    <div>An about page</div>
    <div>An about page</div>
    <div>An about page</div>
    <div>An about page</div>
    <div>An about page</div>
    <div>An about page</div>
    <div>An about page</div>
    <div>An about page</div>
    <div>An about page</div>
    <div>An about page</div>
    <div>An about page</div>
    <div>An about page</div>
    <div>An about page</div>
    <div>An about page</div>
    <div>An about page</div>
    <div>An about page</div>
    <div>An about page</div>
    <div>An about page</div>
    <div>An about page</div>
    <div>An about page</div>
    <div>An about page</div>
    <div>An about page</div>
    <div>An about page</div>
    <div>An about page</div>
    <div>An about page</div>
    <div>An about page</div>
    <div>An about page</div>
    <div>An about page</div>
    <div>An about page</div>
    <div>An about page</div>
    <div>An about page</div>
    <div>An about page</div>
    <div>An about page</div>
    <div>An about page</div>
    <div>An about page</div>
    <div>An about page</div>
    <div>An about page</div>
    <div>An about page</div>
    <div>An about page</div>
</template>